-- ---------------------------------------------------------------------------- --
-- Schema for the trial booking service.
--
-- Identifiers are generated by the application as UUIDv7, so no extension and no
-- database side default is needed here.
-- ---------------------------------------------------------------------------- --

create type booking_status as enum (
    'pending_payment',
    'confirmed',
    'payment_failed',
    'refund_required',
    'expired',
    'cancelled'
);

create type payment_status as enum (
    'initiated',
    'succeeded',
    'failed'
);

create table parents (
    id          uuid        primary key,
    email       text        not null unique,
    full_name   text        not null,
    role        text        not null default 'parent',
    created_at  timestamptz not null default now(),

    constraint parents_role_allowed check (role in ('parent', 'admin'))
);

create table students (
    id          uuid        primary key,
    parent_id   uuid        not null references parents (id) on delete cascade,
    full_name   text        not null,
    grade_level smallint    not null,
    created_at  timestamptz not null default now(),

    constraint students_grade_level_range check (grade_level between 1 and 12)
);

create index ix_students_parent on students (parent_id);

create table trial_classes (
    id               uuid        primary key,
    subject          text        not null,
    title            text        not null,
    starts_at        timestamptz not null,
    duration_minutes smallint    not null default 60,
    capacity         smallint    not null default 4,
    hold_allowance   smallint    not null default 2,
    created_at       timestamptz not null default now(),

    constraint trial_classes_subject_allowed check (subject in ('science', 'math')),
    constraint trial_classes_duration_positive check (duration_minutes > 0),
    constraint trial_classes_capacity_positive check (capacity > 0),
    constraint trial_classes_hold_allowance_not_negative check (hold_allowance >= 0)
);

create table bookings (
    id              uuid           primary key,
    student_id      uuid           not null references students (id),
    class_id        uuid           not null references trial_classes (id),
    status          booking_status not null default 'pending_payment',
    seat_no         smallint,
    hold_expires_at timestamptz,
    confirmed_at    timestamptz,
    created_at      timestamptz    not null default now(),
    updated_at      timestamptz    not null default now(),

    constraint bookings_seat_no_positive check (seat_no is null or seat_no >= 1),
    constraint bookings_confirmed_holds_a_seat check (status <> 'confirmed' or seat_no is not null),
    constraint bookings_confirmed_is_stamped check (status <> 'confirmed' or confirmed_at is not null)
);

create index ix_bookings_class on bookings (class_id);
create index ix_bookings_student on bookings (student_id);
create index ix_bookings_hold_expiry on bookings (hold_expires_at) where status = 'pending_payment';

-- Append only. A row is never mutated after settlement.
create table payment_attempts (
    id              uuid           primary key,
    booking_id      uuid           not null references bookings (id),
    idempotency_key text           not null,
    amount_cents    integer        not null,
    currency        char(3)        not null default 'SGD',
    status          payment_status not null,
    provider_ref    text,
    failure_reason  text,
    created_at      timestamptz    not null default now(),
    settled_at      timestamptz,

    constraint payment_attempts_amount_positive check (amount_cents > 0)
);

create index ix_payment_attempts_booking on payment_attempts (booking_id);

-- Append only audit trail. Feeds the operator surface.
create table booking_events (
    id          uuid           primary key,
    booking_id  uuid           not null references bookings (id),
    from_status booking_status,
    to_status   booking_status not null,
    actor       text           not null,
    reason      text,
    created_at  timestamptz    not null default now(),

    constraint booking_events_actor_allowed check (actor in ('parent', 'system', 'admin', 'payment'))
);

create index ix_booking_events_booking on booking_events (booking_id, created_at);

create table job_queue (
    id           uuid        primary key,
    kind         text        not null,
    payload      jsonb       not null,
    run_after    timestamptz not null default now(),
    attempts     smallint    not null default 0,
    locked_until timestamptz,
    created_at   timestamptz not null default now(),

    constraint job_queue_kind_allowed check (kind in ('expire_hold', 'reconcile_refund')),
    constraint job_queue_attempts_not_negative check (attempts >= 0)
);

-- The claim query orders by run_after and skips locked rows, so this index is
-- what keeps a busy queue from scanning the whole table.
create index ix_job_queue_claimable on job_queue (run_after, id);

-- The access token is a JWT and is stored nowhere. Only the refresh token has a
-- row, and only as a hash.
create table refresh_tokens (
    id         uuid        primary key,
    parent_id  uuid        not null references parents (id) on delete cascade,
    token_hash bytea       not null,
    family_id  uuid        not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now()
);

create index ix_refresh_tokens_family on refresh_tokens (family_id);

-- ---------------------------------------------------------------------------- --
-- Invariants.
--
-- Known gap, stated openly in ADR.md: a check constraint cannot read
-- trial_classes.capacity, so the database stops two bookings sharing a seat
-- number but does not stop a bug assigning seat 9 in a 4 seat class. The upper
-- bound is enforced inside the confirm transaction while the class row is
-- locked.
-- ---------------------------------------------------------------------------- --

-- one live booking per child per class
create unique index uq_booking_active
    on bookings (student_id, class_id)
    where status in ('pending_payment', 'confirmed');

-- two bookings can never own the same seat in a class
create unique index uq_seat_taken
    on bookings (class_id, seat_no)
    where seat_no is not null;

-- a replayed payment submission cannot create a second charge
create unique index uq_payment_idempotency
    on payment_attempts (booking_id, idempotency_key);

-- one row per refresh token, so reuse is detectable
create unique index uq_refresh_token_hash
    on refresh_tokens (token_hash);
